
line.bot:
  channel-token: KTIpaSE1LfT3bPTWZ/zcGYF5BbFu+R7Gx7+qnpkFCfzRc1UXTeXKUQe1pHPVOtKVIzfzU1zKf4AchVEuLXjGPZimdQjNIpbW2T/eVG+CJUkONRc+TP5N1ViFnahaX6AbL71qdzfG1PSk7Xk0r1uazgdB04t89/1O/w1cDnyilFU=
  channel-secret: 5bd34c37f431d318cd45f331f95252fb
  handler.path: /callback